docs : 팔로우 조회 tecspec작성
bottle-note/bottle-note-api-server pull request #122
Opened 2024-06-07 12:50 UTC by 200wonman

팔로우 조회를 위한 tec-spec을 작성했습니다.

Resolves #{이슈-번호}

# 해결하려는 문제가 무엇인가요?

- 서비스 이용자 사이에  팔로우한 유저들의 리스트를 조회하는 기능 구현합니다

# 어떻게 해결했나요?

- 사용자가 팔로우,팔로워 리스트 조회하는 기능 구현이 잘 됐는지 확인 부탁드립니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?

- 전체적인 코드 리뷰 부탁드립니다.
- 예외처리가 잘 됐는지 확인 부탁드립니다.

## 참고 자료

-

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-06-16 20:55 UTC, Whale0928 requested changes
하나의 pr에서 여러 작업이 수행되다 보니 리뷰에 부적절한 혼동이 많이 발생했습니다.

다음 부터는 주의해서 pr을 분리하세요.

또한 물어보고 적용안된게 많은데 이런 부분은 잘 노트해두고 적용하는게 필요해보이네요.

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/controller/FollowCommandController.java
> +import org.springframework.web.bind.annotation.*;
마스터 임포트는 사용하지 마세요 설정을 확인하세요 .
또한 안쓰는 import는 제외하세요, `import app.bottlenote.follow.dto.response.FollowDetail;`는 안쓰는걸로 보이네요.

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/controller/FollowCommandController.java
> +	@GetMapping("/{userId}/follower")
`follow/1/follower` 엔드포인트가 이상하네요?

presentation layer 내에서 분리해도 적절해보이죠?

다시 한번 고민해보세요.

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/controller/FollowCommandController.java
> +	@GetMapping("/{userId}/follow")
`follow / 11 / follow` 이렇게 이상하게 생긴 api가 만들어졌는데 다시 한번 고민해보죠.

`GET follow / 1` 같은 형태로 충분할거 같은데 말이죠

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/dto/request/FollowPageableRequest.java
> +	Long cursor,
정렬타입은 없는게 맞는걸까요?

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/dto/response/FollowDetail.java
> +public class FollowDetail {
주석은 제거해도 될거같고 이것도 레코드로 바꿔보죠

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/repository/CustomFollowRepository.java
> +	PageResponse<FollowSearchResponse> findFollowerList(Long userId, FollowPageableRequest pageableRequest);
presentation layer 부터 계속해서 FollowPageableRequest를 사용하는데 

한번 wrapping 해서 queryDsl를 위한 객체로 가공하죠

지금은 너무 많은 범위에서 사용되네요

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/repository/CustomFollowRepositoryImpl.java
> +		log.info("FollowDetails: {}", followDetails); // []
개발시에 사용한거 같은데 좀더 적절한 로그를 남기죠

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/repository/CustomFollowRepositoryImpl.java
> +		int pageSize = pageableRequest.pageSize().intValue();
왜 int를 꺼낼까요? 별도의 목적이 있는걸까요? 

그리고 가급적 wrapper class를 사용하죠

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/repository/CustomFollowRepositoryImpl.java
> +	private CursorPageable getCursorPageable(
다른 클래스를 구현해서 책임을 분리해보죠

일종의 `supporter` 클래스가 있어도 좋을것 같네요

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/repository/CustomFollowRepositoryImpl.java
> +				ExpressionUtils.as(select(review.count()).from(review).where(review.user.id.eq(follow.followUser.id)), "reviewCount"),
가독성을 위해 메소드로 서브 쿼리를 분리해보죠

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/repository/FollowCommandRepository.java
> +public interface FollowCommandRepository extends JpaRepository<Follow, Long>, CustomFollowRepository {
CustomFollowRepository를 command 레포지토리에서 구현하는게 맞나요?

command는 CUD를 수행하는 역할에 적합한 이름입니다.

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/service/FollowCommandService.java
> +	public PageResponse<FollowSearchResponse> findFollowerList(Long userId, FollowPageableRequest pageableRequest) {
서비스 클래스의 이름을 다시 한번 확인해보죠

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/service/FollowCommandService.java
> +		PageResponse<FollowSearchResponse> followerList = followRepository.findFollowerList(userId, pageableRequest);
인라인으로 처리하는게 더욱 가독성있어 보이네요

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/service/FollowCommandService.java
> +	@Transactional
이 메소드는 readOnly가 빠져있네요? 이런 자잘한 부분은 리뷰시에는 가급적 발견되지 않았으면 하네요.

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/follow/service/FollowCommandService.java
> +	@Transactional(readOnly = true)
👍

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/security/SecurityConfig.java
> +				.requestMatchers("/api/v1/users/nickname").authenticated()
이 경우에는 /api/v1/users는 무조건 인증이 필요할수도 있는데 위와 같이 와일드카드(*)를 고려해보죠

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/controller/UserCommandController.java
>  	public ResponseEntity<GlobalResponse> nicknameChange(@RequestBody @Valid NicknameChangeRequest nicknameChangeRequest) {
이 pr과 매우 적합하지 않은 기능 수정인데

다음부터는 pr을 분리해서 작업하도록 하죠

2024-06-16 20:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/controller/UserCommandController.java
> +			.orElseThrow(() -> new UserException(UserExceptionCode.USER_NOT_FOUND));
적절한 `UserExceptionCode`를 사용했는지 고민해보죠

2024-06-16 20:55 UTC, Whale0928 commented on src/test/java/app/bottlenote/user/service/UserCommandServiceTest.java
> +		Long userId = 1L;
다른 코드를 분석해서 fixture 클래스를 고려해보죠

fixture는 테스트 시 필요한 객체등을 준비해주는 클래스입니다.

2024-06-16 20:56 UTC, Whale0928 commented
추가적으로 병합된 main와 한번 병합하고 진행하도록 하세요.
wiki 관련 수정 사항이 적용되었습니다.

2024-06-17 00:52 UTC, 200wonman commented on src/main/java/app/bottlenote/follow/controller/FollowCommandController.java
> +import org.springframework.web.bind.annotation.*;
넵...!!

2024-06-22 13:04 UTC, Whale0928 approved these changes
👀

2024-06-23 05:41 UTC, merged