Pr/121 내가 작성한 리뷰 조회
bottle-note/bottle-note-api-server pull request #125
Opened 2024-06-09 10:01 UTC by chadongmin

Resolves #{이슈-번호}
#121 

# 해결하려는 문제가 무엇인가요?
- 내가 작성한 리뷰 조회 기능을 구현하고, 테스트 코드, restdocs작성했습니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?
- 리뷰 부탁드립니다.

## 참고 자료

-

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-06-09 13:16 UTC, Whale0928 requested changes
전체적으로 큰 문제는 없습니다 몇몇 개선 사항이 있으니 확인 후 수정해주세요.
그리고 코멘트를 요청한거 말고도 제가 수정을 지적한 부분은 코멘트로 왜 이렇게 작성했었는지를 작성해보세요 . 재귀학습에 굉장히 큰 도움이 됩니다.

- 메인 병합과 병합을 한번 진행하고 수정하세요 충돌이 있을거같네요.
- 이제 테스트가 좀 반복작업이 되는것 처럼 느껴질탠대 뭐가 지루하고 뭐가 단점일까를 한번씩 확인해보세요.

2024-06-09 13:16 UTC, Whale0928 commented on docs/tech-spec/review/my-review-read-techspec.md
> +- 내가 작성한 리뷰를 조회할 위스키 ID
내가 작성한 리뷰는 페이지가 필요 없을까요?
몇백개 이상을 리뷰할 수도 있을것 같은데 .
한번더 확인해볼만한 포인트인것 같네요

2024-06-09 13:16 UTC, Whale0928 commented on docs/tech-spec/review/my-review-read-techspec.md
> +- 내가 작성한 리뷰를 조회하려고 하는 유저가 로그인 한 유저인지?
이 문장은 좀 이해하기 어려운것 같아요 . 
좀 더 편하게 작성되어야 할것 같아요.

예를 들어
-`본인의 목록만 조회하는 지`

2024-06-09 13:16 UTC, Whale0928 commented on src/docs/asciidoc/api/review/my-review-read.adoc
> +- Authorization 헤더에 액세스 토큰을 첨부하지 않으면`토큰이 존재하지 않습니다` 에러 메시지가 출력됩니다 (400)
이 예외들은 이 api의 오류일까요 ?
앞으로 인증이 필요한 모든 문서에 이 문장이 들어오게 되면 매우 지저분해질탠대
유저 인증 인가 관련 문서에서 소개하면 더 좋겟죠 ? 

예를 들어 개요 아래 `1.4. 인증 인가` 혹은 `3 회원 하위`에 추가되도 좋을거같네요

2024-06-09 13:16 UTC, Whale0928 commented on src/docs/asciidoc/api/review/my-review-read.adoc
> +- 유저의 ID가 존재하지 않으면 UserException이 발생합니다.
UserException은 서버에서만 사용되는 custom exception입니다.
클라이언트에는 `정상적인 유저만 조회 가능합니다. ` , `존재하는 사용자만 조회 가능합니다.` 
같이 수정해보죠

2024-06-09 13:16 UTC, Whale0928 commented on src/docs/asciidoc/api/review/my-review-read.adoc
> +PathVariable로 alcoholId를 전달합니다.
아래와 동일하지만 요청 경로에 조회 할 알코올의 식별자가 포함되어야합니다 같이 표현하는게 더 적절하겟네요

2024-06-09 13:16 UTC, Whale0928 commented on src/docs/asciidoc/api/review/my-review-read.adoc
> +GET /api/v1/reviews/me/{alcoholId}
/api/v1/reviews/{alcoholId} 가 리뷰조회인대. 
 내 리뷰 조회는 
  /api/v1/reviews/{alcoholId}/me 가 더 적절해 보이죠?

2024-06-09 13:16 UTC, Whale0928 commented on src/docs/asciidoc/api/review/my-review-read.adoc
> +GET /api/v1/reviews/me/{alcoholId}
추가적으로 왜 me를 중간에 끼웠는지는 코멘트로 남겨주세요  잘못된점이 아니라 왜 이렇게 선택했는지 재귀해보라는 의미에요.

2024-06-09 13:16 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/image/ImageUtil.java
> +package app.bottlenote.global.image;
common이 있는데 왜 global이 되었을까요 ?

2024-06-09 13:16 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/image/ImageUtil.java
>  public class ImageUtil {
전체적으로 하드코딩이 매우 심한대 추후 리팩토링 대상이 되야할것 같네요 
이슈로 등록해두시죠

2024-06-09 13:16 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +			() -> new UserException(USER_NOT_FOUND)
NOT_FOUND 보다 required 가 이미 있을탠대 그게 더 직관적이겟죠?
이 부분의 문제는 유저를 못찾은게 아니라 있어야하는데 없는거니깐요

2024-06-09 13:16 UTC, Whale0928 commented on src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
> +		try (MockedStatic<SecurityContextUtil> mockedValidator = mockStatic(
다른 클래스에서 어떻게 사용하고 잇는지 확인 한번 해보죠

2024-06-09 13:16 UTC, Whale0928 commented on src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
> +	private PageResponse<ReviewResponse> getMyReviewResponse() {
이 클래스는 테스트라는 목적이 클래스입니다.
이 메소드의 경우에는 테스트라는 목적을 달성하기 위해 "값"을 준비하는 거죠
다만 준비하기 위해 클래스 전체의 가독성을 강하게 방해하고 있어요
fixture라는 걔념을 확인해서 클래스를 분리해보죠
다른 패키지에 예시로 구현해둔걸 확인해보세요

2024-06-12 05:52 UTC, chadongmin commented on docs/tech-spec/review/my-review-read-techspec.md
> +- 내가 작성한 리뷰를 조회할 위스키 ID
페이지네이션 관련 쿼리파라미터 추가하여 반영했습니다!

2024-06-12 05:54 UTC, chadongmin commented on docs/tech-spec/review/my-review-read-techspec.md
> +- 내가 작성한 리뷰를 조회하려고 하는 유저가 로그인 한 유저인지?
`내가 작성한 리뷰`를 조회할 수 있는건 당연히 작성한 `본인`만 조회할 수 있는거 아닌가요
더 생각해보겠습니다.

2024-06-12 05:55 UTC, chadongmin commented on src/docs/asciidoc/api/review/my-review-read.adoc
> +- Authorization 헤더에 액세스 토큰을 첨부하지 않으면`토큰이 존재하지 않습니다` 에러 메시지가 출력됩니다 (400)
1.4 공통 인증/인가 섹션을 추가해서 중복된 부분을 제거했습니다.

2024-06-12 05:56 UTC, chadongmin commented on src/docs/asciidoc/api/review/my-review-read.adoc
> +- 유저의 ID가 존재하지 않으면 UserException이 발생합니다.
반영했습니다.

2024-06-12 05:56 UTC, chadongmin commented on src/docs/asciidoc/api/review/my-review-read.adoc
> +PathVariable로 alcoholId를 전달합니다.
`요청 경로에 조회 할 알코올의 식별자가 포함되어야 합니다. 알코올의 식별자는 Long 타입입니다.`
와 같은 직관적인 문장으로 수정했습니다.

2024-06-12 05:57 UTC, chadongmin commented on src/main/java/app/bottlenote/global/image/ImageUtil.java
> +package app.bottlenote.global.image;
common하위에 위치하도록 수정했습니다. Global보다는 common이 맞는 것 같네요. 놓친 부분 알려주셔서 감사합니다.

2024-06-12 05:58 UTC, chadongmin commented on src/main/java/app/bottlenote/global/image/ImageUtil.java
>  public class ImageUtil {
등록했습니다!

2024-06-12 05:58 UTC, chadongmin commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +			() -> new UserException(USER_NOT_FOUND)
`REQUIRED USER ID` 에러 메시지로 수정했습니다.

2024-06-12 07:46 UTC, chadongmin commented on src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
> +		try (MockedStatic<SecurityContextUtil> mockedValidator = mockStatic(
반영했습니다!

2024-06-12 07:46 UTC, chadongmin commented on src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
> +	private PageResponse<ReviewResponse> getMyReviewResponse() {
네 다른 테스트코드 참고하여 fixture 클래스로 분리하였습니다.

2024-06-12 14:14 UTC, Whale0928 approved these changes
→

2024-06-12 15:58 UTC, merged