Pr/124 토큰 검증 실패시 예외처리 개선
bottle-note/bottle-note-api-server pull request #126
Opened 2024-06-09 10:15 UTC by chadongmin

Resolves #{이슈-번호}
#124 

# 해결하려는 문제가 무엇인가요?
- 토큰이 검증에 통과하지 못할시 모두 "잘못된 토큰입니다"라는 동일한 에러메시지를 출력하는 문제
- HTTP STATUS는 401이지만 응답 Resposne의 code는 403으로 동일하지 않은 문제

# 어떻게 해결했나요?

- 기존에는 jwtTokenValidator에서 예외를 처리하고 있었는데, log.debug로 로그만 찍는 처리를 하고 있었습니다.
- jwtTokenValidator에서는 예외를 던지도록 수정 후, jwtTokenValidator를 호출하는 jwtAuthenticationFilter에서 예외를 처리하도록 수정했습니다. 

- jwtAuthenticatioinFilter에서는 예외를 잡아서 HttpServletRequest에 예외를 삽입합니다.
- 예외를 처리하는 GlobalExceptionHandler에서도 고정적으로 403을 반환했지만, 어떤 예외인지에 따라서 상태코드와 에러메시지를 각각 반환하도록 분기처리하여 수정했습니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?
- 적절하게 구현되었는지 리뷰해주세요

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-06-09 13:27 UTC, Whale0928 requested changes
과도한 if else를 Excetion handler를 이용하지 말고 enum 의 메소드를 추가해 컨텍스트를 분리해보죠.
또한 매우 많은 검증이 필요할탠대 테스트가 불가능한가?를 한번 고민해보시죠.

2024-06-09 13:27 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/exception/handler/GlobalExceptionHandler.java
> +		if (e instanceof SignatureException) {
Custom Jwt Exception을 활용해 개선해볼수 있겟죠?

2024-06-12 13:53 UTC, chadongmin commented on src/main/java/app/bottlenote/global/exception/handler/GlobalExceptionHandler.java
> +		if (e instanceof SignatureException) {
enum 활용하는 메서드 구현해서 if else 로직 제거하고 가독성을 높였습니다. 리뷰 부탁드립니다.

2024-06-12 14:16 UTC, Whale0928 submitted a review, later dismissed

2024-06-13 06:50 UTC, merged