Pr/120 리뷰 수정 기능
bottle-note/bottle-note-api-server pull request #134
Opened 2024-06-19 07:59 UTC by chadongmin

Resolves #{이슈-번호}
#120

# 해결하려는 문제가 무엇인가요?

- 리뷰 수정 기능을 구현 및 테스트코드를 작성했습니다.

- 리뷰 조회 시 tasingTagList를 조회하지 않고 있어서 추가했습니다.
- review_tasting_tag 테이블에 사용자가 리뷰 등록시에 첨부한 테이스팅 태그가 여러 row로 쌓여서 단일 쿼리로 조회가 불가능했습니다.

# 어떻게 해결했나요?

- 별도의 테이스팅 태그를 조회하는 쿼리를 작성해서 DTO에 끼워넣는 형태로 구현했는데, 리팩토링이 필요할 것 같습니다(이슈로 분리해놓겠습니다)

# 어떤 부분에 집중하여 리뷰해야 할까요?

## 참고 자료

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-06-19 12:02 UTC, Whale0928 requested changes
디스코드를 통해 이야기한 내용들을 수정해주세요.

2024-06-19 12:02 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +	@PatchMapping("/{alcoholId}")
alcoholId 가 아닌거 같네요

2024-06-21 08:18 UTC, Whale0928 requested changes
어제 이야기를 많이 했는데, 의미와 다르게 적용된것들이 주로 보이네요.
만약 도메인 서비스를 적절하게 사용했다면 이런식으로 구현되었을겁니다.

```java
@Transactional
    public ReviewModifyMessage modifyReview(
		Long reviewId,
		Long currentUserId,
		ReviewModifyRequest reviewModifyRequest
	) {
        // 리뷰 조회
        Review review = reviewRepository.findByIdAndUserId(reviewId, currentUserId)
            .orElseThrow(() -> new ReviewException(REVIEW_NOT_FOUND));

         // ReviewModifyVO 생성 및 유효성 검사
        ReviewModifyVO reviewModifyVO = reviewValidationService.createValidatedReviewModifyVO(reviewModifyRequest);

        // 리뷰 수정
        review.modifyReview(reviewModifyVO);
        
        // 태그 업데이트
        reviewTagService.updateTags(review, reviewModifyRequest.getTastingTagList());

        // 이미지 업데이트
        reviewImageService.updateImages(review, reviewModifyRequest.getImageUrlList());

        // 리뷰 저장
        reviewRepository.save(review);

        return ReviewModifyMessage.success;
    }
```

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/Review.java
> +	private Set<ReviewTastingTag> reviewTastingTags = new HashSet<>();
태그 목록을 조회하기 위해 연관관계가 새롭게 생겼는데

이제 슬슬 일급 컬렉션에 대해서도 고민해볼 타임인것같네요

일급컬렉션을 조사해보고 내일 미팅시에 이야기하면 좋겟네요

향로님의 글을 읽어보세요

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewDomainService.java
> +	public Set<ReviewTastingTag> createValidatedReviewTastingTag(List<String> tastingTags, Review review) {
tag -> tags

이 메소드가 그냥 비지니스 서비스에서 태그 목록을 생성하는것과 뭐가 다른가요?
한번 고민해보죠

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewDomainService.java
> +	public ReviewModifyVO createValidatedReview(ReviewModifyRequest reviewModifyRequest) {
이럴 경우 책임을 넘겨주는 메소드라면 적절한 검증이 필요해보이네요

지금은 그냥 ReviewModifyVO의 빌더 메소드와 다를게 없네요 

만약 이렇다면 ReviewModifyVo 내부 request를 전달해도 될것 같네요

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewDomainService.java
> +public class ReviewDomainService {
도메인 서비스는 도메인의 논리를 처리하는 서비스입니다.

`도메인`의 비지니스의 규칙의 검증 , 데이터 유효성 검사가 핵심입니다. 

도메인의 책임이 아닌건 비지니스 서비스 레이어에서 처리하도록 하죠

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewDomainService.java
> +			.map(tastingTag -> ReviewTastingTag.builder()
이 정도 생성자라면 정적팩토리패턴의 생성자가 더 가독성 있어보여요. `.create(review,tag)`

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +	public static final String REVIEW_MODIFY_RESPONSE = "리뷰 수정이 완료되었습니다";
수정에대한 응답 메시지인대

이 클래스에서 구현될 모든 메소드들이 참조되는 값으로 구현되었네요

적어도 Enum으로 관리하죠

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewTastingTag.java
>  	private static final int TASTING_TAG_MAX_LENGTH = 12;
코드의 종류마다 있는 자리는 보통 정해져있습니다. 상수는 기본적으로 촤상단에 위치시키죠

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewDetail.java
> -	public ReviewDetail(
응답객체는 Response을 붙이는 약속이 있죠

상세조회용 응답객체면 response 키워드가 필요해보이네요

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +	private void updateReviewTastingTags(Review review, List<String> requestedTastingTag) {
reviewTastingTagRepository는 필요 없고 앞으로 지워가면서 개발할거라고 이야기했습니다

리뷰에게 태그의 변경을 부탁해야지 직접 등록은 ❌

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewDomainService.java
> +package app.bottlenote.review.domain;
도메인에 위치하는 서비스가 도메인서비스가 아닙니다

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +			reviewTastingTagRepository.deleteByReviewId(review.getId());
리뷰에게 요청하면 이런 로직도 필요없게 됩니다.

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewDomainService.java
> +	public ReviewModifyVO createValidatedReview(ReviewModifyRequest reviewModifyRequest) {
create validated review는 검증된 리뷰를 생성한다 인대  이 메소드는 검증된 리뷰 업데이트 오브젝트를 생성하기 위한거죠 ? 메소드 명은 동작 자체를 설명하도록 하죠.

2024-06-21 08:18 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewModifyVO.java
> +package app.bottlenote.review.domain;
VO도 동일합니다

2024-06-22 04:54 UTC, chadongmin commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +	@PatchMapping("/{alcoholId}")
수정했습니다!

2024-06-22 13:11 UTC, chadongmin commented on src/main/java/app/bottlenote/review/domain/Review.java
> +	private Set<ReviewTastingTag> reviewTastingTags = new HashSet<>();
넵 !

2024-06-22 13:11 UTC, chadongmin commented on src/main/java/app/bottlenote/review/domain/ReviewDomainService.java
> +	public ReviewModifyVO createValidatedReview(ReviewModifyRequest reviewModifyRequest) {
수정했습니다!

2024-06-22 13:12 UTC, chadongmin commented on src/main/java/app/bottlenote/review/domain/ReviewDomainService.java
> +public class ReviewDomainService {
넵 수정했습니다

2024-06-23 12:34 UTC, Whale0928 reviewed
서포트 서비스에 작성한 내용은 두개 모두 적용됩니다.

2024-06-23 12:34 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +	public ReviewModifyVO createReviewEntity(ReviewModifyRequest reviewModifyRequest) {
왜 다시 서비스로 나왔을까요

퍼블릭이면 모든 곳에서 이 Vo를 생성할 수 있는데 맞는걸까요?
priv-pro/priv으로 선언하거나 vo내부에서 request를 받는 생성자를 받는게 필요해보이네요

2024-06-23 12:34 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +public class ReviewTastingTagSupportService {
왜 항상 service라는 키워드를  작성하는지 고민해보세요
그냥 생각없이 서비스 키워드를 붙이는지 아니면 무슨 이유가 있는지

2024-06-23 12:34 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +	private final ReviewTastingTagRepository reviewTastingTagRepository;
이 리포지토리는 의존성이 없어야한다고 계속 말하고 있어요,

2024-06-23 12:34 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +		if (CollectionUtils.isEmpty(tastingTags)) {
empty도 검사하는데 맞나요 ? 
비지니스 규칙을 다시 생각해보죠

2024-06-23 12:34 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +			.distinct() // 중복 제거
distinct를 굳이 선언하는 이유가 뭘까요? set인대?

2024-06-23 12:34 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +			.map(tastingTag -> ReviewTastingTag.builder()
2개인대 빌더 패턴은 가독성을 해치네요

2024-06-23 12:34 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +
이렇게 소극적인 메소드를 구현할거면 이름이라도 최대한 정확하게 작성하죠
검증이라는 동작보다 최대 등록횟수의 오버플로를 방지하는 역할만 하는 메소드로만 보이네요

2024-06-23 14:26 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +public class ReviewTastingTagSupportService {
비스니스 로직을 처리하니까 서비스를 붙였는데 혹시 잘못됐다면 알려주시면 감사하겠슴다
현기님은 어떻게 생각하시는지 알려주시죵

2024-06-23 14:26 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +public class ReviewTastingTagSupportService {
ReviewTastingTagSupport까지만 쓰는게 적절한가요?

2024-06-23 14:29 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +public class ReviewTastingTagSupportService {
이건 비지니스 로직이 아니고 도메인 로직인대 , 개발자는 둘을 분명 다르게 봐야하거든요 그렇다면 혼동의 가능성을 제외하기 위해 service라는 단어는 잘 명시하지 않아요, 제가 서포터나 콜라보, 핸들러 같이 다른 단어들을 이야기 했던것도 거기서 파생되는거고요

2024-06-23 15:37 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +
checkMaxSize로 수정해서 직관적이도록 수정했어요

2024-06-23 15:37 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +	public ReviewModifyVO createReviewEntity(ReviewModifyRequest reviewModifyRequest) {
메서드 삭제하고, 생성자에서 ReviewModifyRequest만 생성 가능하도록 제한했습니다.

2024-06-23 15:38 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +			.distinct() // 중복 제거
수정했습니다.

2024-06-23 15:38 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +			.map(tastingTag -> ReviewTastingTag.builder()
수정했습니다.

2024-06-23 15:40 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +		if (CollectionUtils.isEmpty(tastingTags)) {
이 부분도 수정했습니다

2024-06-23 15:43 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewTastingTagSupportService.java
> +public class ReviewTastingTagSupportService {
네 이해했습니다. 감사합니다

2024-06-23 15:46 UTC, Whale0928 submitted a review, later dismissed
👍

2024-06-23 15:52 UTC, merged