Pr/135 리뷰 삭제 기능
bottle-note/bottle-note-api-server pull request #138
Opened 2024-06-24 14:24 UTC by chadongmin

Resolves #{이슈-번호}
#135 

# 해결하려는 문제가 무엇인가요?
- 리뷰 삭제 기능을 구현했습니다.
- 단위테스트 및 컨트롤러 테스트를 구현했습니다.
- RestDocs 문서화를 작성했습니다
 
- 리뷰가 삭제되면 active_stauts 컬럼의 값이 `ACTIVE` ->   `DELETED` 로 변경되도록 구현했습니다.
- Likes가 먼저 삭제되지 않아 외래키 제약조건으로 리뷰 삭제가 안되는 문제가 있었습니다. 

# 어떻게 해결했나요?

- 리뷰 엔티티에서 Likes 엔티티와 @OneToMany로 연관관계를 맺고 Cascade ALL, orphanRemoval=true 옵션으로 영속성이 전파되도록 하여 해결했습니다.

-  조회 쿼리에 활성상태의 리뷰만 조회하는 where절을 추갛ㅆ습니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?

-

## 참고 자료

-

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-06-26 09:20 UTC, Whale0928 requested changes
몇몇 수정사항이 있습니다.
코드를 쓸때 한번씩 더 고민해서 작성하도록 하죠
궁금한점이 있다면 디스코드로 연락주세요.

2024-06-26 09:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/security/SecurityConfig.java
> +				.requestMatchers(HttpMethod.DELETE, "api/v1/reviews/**").authenticated()
Get 만 .permitAll() 하고 다른 모든걸 .authenticated() 처리하면 깔끔해질것 같네요

2024-06-26 09:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/constant/ReviewActiveStatus.java
> +public enum ReviewActiveStatus {
상태 관련이 없다고 이야기 했는데 ReviewStatus가 이미 있네요? 다시 한번 확인해보시죠

2024-06-26 09:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/constant/ReviewResponse.java
>  public enum ReviewResponse {
결과 메시지라는 상수 집합이라는 걸 좀더 명확하게 나타내죠

2024-06-26 09:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/Review.java
> +	private ReviewActiveStatus activeStatus = ReviewActiveStatus.ACTIVE;
`ReviewStatus status` 와 차이점이 뭔지 확인해보세요

2024-06-26 09:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		if (review.getActiveStatus().equals(DELETED)) {
이미 삭제된 경우에 이미 삭제되었다고 응답하는건 도메인 규칙이죠 

비지니스 서비스는 삭제일때는 ALREADY_DELETED가 반환된다는걸 몰라야합니다.

2024-06-26 09:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +	public String deleteReview(Long reviewId, Long currentUserId) {
String 을 반환하지 마세요 가급적 enum을 넘기고 적어도 컨트롤러에서 수정해서 전달하죠

2024-06-26 09:20 UTC, Whale0928 commented on src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
> +		when(reviewService.modifyReviews(any(ReviewModifyRequest.class), any(), any())).thenReturn("리뷰 수정이 성공적으로 완료되었습니다.");
검증을 할거면 이넘을 가져오면 더 편하고 정확하게 되겟죠?

2024-06-26 09:20 UTC, Whale0928 commented on src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
> +	void review_delete_test() throws Exception {
별개로 해당 테스트 클래스에서 fixture를 만들거면 정확하게 만들죠 어떤건 픽스쳐에서 가져오고 어떤건 클래스 내부에서 만들고 있네요

2024-06-26 09:20 UTC, Whale0928 commented on src/test/java/app/bottlenote/review/controller/ReviewDeleteControllerTest.java
> +public class ReviewDeleteControllerTest {
저번에도 말했는데 ReviewDeleteController 라는 컨트롤러는 없는데 

지금 ReviewDeleteController 자체를 테스트 하는것 같은 이름을 가지고 잇어요

삭제에 관련된것만 테스트하는거면 정확하게 표기하죠. 

리뷰하는 사람도 이런 컨트롤러가 있어? 하면서 찾아보게 되서 매우 번거로워요

2024-06-26 09:20 UTC, Whale0928 commented on src/test/java/app/bottlenote/review/controller/ReviewDeleteControllerTest.java
> +	public static final String response = "리뷰 삭제가 성공적으로 완료되었습니다.";
이미 상수로 선언 됬으니깐 필요없겟죠?

2024-06-26 09:20 UTC, Whale0928 commented on src/test/java/app/bottlenote/review/controller/ReviewDeleteControllerTest.java
> +			.andExpect(status().isOk())
응답 값도 같이 검증하죠

2024-06-26 09:20 UTC, Whale0928 commented on src/test/java/app/bottlenote/review/service/ReviewDeleteServiceTest.java
> +		alcohol = Alcohol.builder()
이런 지저분한 준비 코드를 정리하기 위해 fixture가 있어요 활용해보죠

2024-06-26 09:20 UTC, Whale0928 commented on src/test/java/app/bottlenote/review/service/ReviewDeleteServiceTest.java
> +		reviewService.deleteReview(reviewId, userId);
응답값을 반환받아서 그걸 검증받아야겟죠 ? 

지금 하는건 서비스 테스트인대 검증이 이상하네요

2024-06-26 09:20 UTC, Whale0928 commented on src/test/java/app/bottlenote/review/service/ReviewDeleteServiceTest.java
> +}
이미 삭제된 경우에는 삭제되었다고 반환할거면 그것도 검증하면 좋겟네요

2024-06-26 09:49 UTC, Whale0928 commented
추가적으로 `ReviewModifyVO`의 위치 도메인에서 뺴라고 했는데 또 누락됬네요 . 미팅 시에 이야기한건 놓치지 말고 적용하세요.

2024-06-27 04:59 UTC, chadongmin commented on src/main/java/app/bottlenote/global/security/SecurityConfig.java
> +				.requestMatchers(HttpMethod.DELETE, "api/v1/reviews/**").authenticated()
반영해서 수정했습니다

2024-06-27 05:20 UTC, chadongmin commented on src/main/java/app/bottlenote/review/domain/constant/ReviewResponse.java
>  public enum ReviewResponse {
ReviewResponseMessage로 수정했습니다.

2024-06-27 05:20 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		if (review.getActiveStatus().equals(DELETED)) {
수정했습니다

2024-06-27 05:20 UTC, chadongmin commented on src/test/java/app/bottlenote/review/controller/ReviewDeleteControllerTest.java
> +	public static final String response = "리뷰 삭제가 성공적으로 완료되었습니다.";
수정했습니다!

2024-06-27 05:20 UTC, chadongmin commented on src/test/java/app/bottlenote/review/service/ReviewDeleteServiceTest.java
> +		alcohol = Alcohol.builder()
모든 테스트코드를 Fixture 사용하도록 수정했습니다.

2024-06-27 05:20 UTC, chadongmin commented on src/test/java/app/bottlenote/review/controller/ReviewDeleteControllerTest.java
> +			.andExpect(status().isOk())
반영했습니다!

2024-06-27 05:21 UTC, chadongmin commented on src/test/java/app/bottlenote/review/service/ReviewDeleteServiceTest.java
> +		reviewService.deleteReview(reviewId, userId);
수정했습니다!

2024-06-27 09:39 UTC, Whale0928 reviewed
응답값만 수정하고 나머지는 어느정도 됬을것같으니 넘어가죠

2024-06-27 09:39 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +			success(reviewService.deleteReview(reviewId, currentUserId).getDescription())
이렇게 보내게 되면 단순 String만 보내게 되면 결과가

`data:쏼라쏼라 ~` 이런식으로 되는데 우리는 보통

`data:
      message:  쏼라쏼라
`
이런 구조로 가죠 예시로 pr129의 `ReviewReplyResultResponse`를 확인해보세요

2024-06-27 12:31 UTC, chadongmin commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +			success(reviewService.deleteReview(reviewId, currentUserId).getDescription())
pr129 참고해서 반영했습니다

2024-06-27 12:31 UTC, chadongmin commented on src/main/java/app/bottlenote/review/dto/response/ReviewResultResponse.java
> +	}
이렇게 ReviewResultResponse로 감싸서 반환하도록 수정했습니다. 확인부탁드려요

2024-06-27 12:34 UTC, Whale0928 approved these changes
👀

2024-06-27 12:37 UTC, merged