리뷰 상세 조회 기능
bottle-note/bottle-note-api-server pull request #147
Opened 2024-06-28 15:09 UTC by chadongmin

Resolves #{이슈-번호}
#136 

# 해결하려는 문제가 무엇인가요?

- 리뷰 상세조회 기능을 구현합니다.
- 리뷰 상세조회 테스트코드를 작성합니다.

# 어떻게 해결했나요?

-

# 어떤 부분에 집중하여 리뷰해야 할까요?

-

## 참고 자료

-

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-06-30 14:07 UTC, Whale0928 requested changes
몇몇 수정사항을 검토후 테스트 코드가 구현되면 될것 같네요

루트 브랜치는 수시로 동기화를 신경쓰죠.

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/AlcoholInfo.java
> +package app.bottlenote.review.dto.response;
`AlcoholDomainSupport`에 협력을 요청하고 이 객체를 응답 받으니 이 객체도 alcohol 쪽에 있는게 의존성이 맞겟죠?

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/AlcoholInfo.java
> +public class AlcoholInfo {
record 되는 객체는 record로 다루죠

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewReplyInfo.java
> +public class ReviewReplyInfo {
record 되는 객체는 record로다루죠

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewDetailResponse.java
> +public record ReviewDetailResponse(
얘는 레코드로 잘 되었네요

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
>  public class ReviewResponse {
이 클래스도 레코드로 만들고 최초 생성시 빈 리스트로 초기화하고 리스트에 add해서 바꾸는 식으로 변경해보죠.

 페이지네이션값 초기화 하는것 처럼 받으면 됩니다 초기화된 리스트는 final이여도 값 변경이 가능합니다.

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		if (alcoholDomainSupport.existsByAlcoholId(reviewCreateRequest.alcoholId()).equals(FALSE)) {
이 부분은 뭔가 잘못 됬네요?
예외를 던질거면 `alcoholDomainSupport.existsByAlcoholId()`에서만 처리하도록 하죠
여기서는 AlcoholException를 던지지 말고. 그냥 `alcoholDomainSupport.적절한 식별자인가?()`호출만 하죠

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		if (userDomainSupport.existsByUserId(currentUserId).equals(FALSE)) {
위와 동일 여기서는 ReviewException만 던져져야해요 이 구조를 가져갈 거면 적어도 ReviewException을 던지도록 하죠

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> -		Long alcoholId,
조금 거슬리는데 가급적 순서를 맞추죠 , 
1. 식별자 
2. 식별자
3. dto
같이 타입 순서는 맞추도록 하죠

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		List<ReviewImageInfo> reviewImageInfos = new ArrayList<>();
스트림을 활용해서 한번에 초기화 하죠 선언과 초기화가 나눠져 있을 필요가 없는것 같네요

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		review.getReviewImages()
`review
    .getReviewImages()
    .stream()
    .map(image->ReviewImageInfo.create(image.getOrder(), image.getImageUrl()) )
    .toList()`

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		List<ReviewReplyInfo> reviewReplies = reviewRepository.getReviewReplies(reviewId);
레포지토리에서 꺼내지 말고 위에서 조회한 `Review`에서 꺼내보죠
위와 같이 바로 `map()`을 통해 ReviewReplyInfo로 만들수도 있어요.
Lazy Loding을 잘 생각해서 해보죠.

2024-06-30 14:07 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		Review review = reviewRepository.findByIdAndUserId(reviewId, currentUserId).orElseThrow(() -> new ReviewException(REVIEW_NOT_FOUND));
. 기준으로 줄넘김이 잇으면 됩니다. `.orElseThrow` 계속해서 일관성 없는 포멧팅이 보이네요.

2024-06-30 14:07 UTC, Whale0928 commented on src/test/java/app/bottlenote/alcohols/fixture/InMemoryAlcoholQueryRepository.java
> +import app.bottlenote.review.dto.response.AlcoholInfo;
위에서 이야기한 부분인대 alcohols 패키지인대 review 의존성이 생기죠 ? 
이런 부분을 신경 쓰면 의존성 관리가 편해집니다.

2024-06-30 14:07 UTC, Whale0928 commented on src/test/java/app/bottlenote/alcohols/fixture/InMemoryAlcoholQueryRepository.java
> +	public AlcoholInfo findAlcoholInfoById(Long alcoholId, Long userId) {
도메인 하위의 AlcoholQueryRepository 에도 추가되면 javadoc도 확인이 필요합니다.

pr 상에서는 추가된 내역이 보이진 않네요 한번 확인해보죠.

2024-07-01 23:50 UTC, chadongmin commented on src/main/java/app/bottlenote/review/dto/response/AlcoholInfo.java
> +public class AlcoholInfo {
수정했습니다

2024-07-01 23:51 UTC, chadongmin commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
>  public class ReviewResponse {
ReviewResponse는 Querydsl로 생성자 주입하는 방식인데, record로 바꾸면 List타입으로 되어 있는 reviewTastingTag도 반드시 생성자에 포함되어야 합니다. 그러면 Querydsl 생성자 주입하는 시점에 collection 값을 주입할 수 없어서 오류가 발생합니다. 이건 그대로 가는게 좋을 것 같다고 생각하네요

2024-07-01 23:51 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		review.getReviewImages()
수정했습니다!

2024-07-01 23:53 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		List<ReviewReplyInfo> reviewReplies = reviewRepository.getReviewReplies(reviewId);
이 부분은 map을 사용해서 ReviewReplyInfo의 Builder를 호출해서 초기화 해야 하는데, 초기화 해야 하는 필드 중에 username, nickname이 포함되어 있습니다. 조회한 Review가 User객체를 참조하고 있지 않고 UserId만 가지고 있게 수정되어서, username, nickname을 가지고 오려면 Review에서 참조한 UserId로 다시 User객체를 참조해야 하는데, 그러면 너무 로직이 무거워지는 것 같아서 Querydsl에서 한번에 조인하는게 더 나을 것 같습니다.

2024-07-01 23:56 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
>  public class ReviewResponse {
정말 주입 할수 없는지를 다시 생각해보세요 가능합니다.

2024-07-02 00:03 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		List<ReviewReplyInfo> reviewReplies = reviewRepository.getReviewReplies(reviewId);
좀 읽기 쉽게 줄넘김 좀 사용하죠
리뷰 댓글 정보에 바로 접근 불가한 값이 있어서 dto injection이 편하다면 그래도 좋을것같네요
`username, nickname이 ` email을 의미한거겟죠?

2024-07-06 06:35 UTC, chadongmin commented on src/main/java/app/bottlenote/review/service/ReviewImageSupport.java
> +	public List<ReviewImageInfo> getReviewImageInfo(Review review) {
이 부분을 reviewService에서 ReviewImageSupport로 옮겼습니다

2024-07-06 07:08 UTC, Whale0928 reviewed
:eyes

2024-07-06 07:08 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/service/domain/UserDomainSupport.java
> -	Boolean existsByUserId(Long userId);
javadoc과 메소드에서 boolean를 반환하도록 되어있는 메소드입니다, 수정이 아닌 다른 메소드를 생성하거나 호출하도록 수정하죠

2024-07-06 07:08 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewImageSupport.java
> +	public List<ReviewImageInfo> getReviewImageInfo(List<ReviewImage> reviewImages) {
이렇게 들어 컬렉션은 nul 체크는 필요하겟죠

2024-07-06 07:08 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/service/domain/DefaultAlcoholDomainSupport.java
> +	public void existsByAlcoholId(Long alcoholId) {
boolean 을 반화하도록 수정이 필요해보이네요

2024-07-06 07:08 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/service/domain/DefaultAlcoholDomainSupport.java
> +		return alcoholQueryRepository.findAlcoholInfoById(alcoholId, userId);
없을때는 null 일탠대 이럴때는 옵셔널 객체를 활용하는게 적절해보이네요. `AlcoholInfo.empty()` 같은 방식도 고려해볼만 하네요.

2024-07-06 07:08 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/service/domain/DefaultAlcoholDomainSupport.java
> +	public Optional<Alcohol> findById(Long alcoholId) {
도메인 서비스는 도메인 전체를 노출하기 않기 위해 사용되는데 , 이건 규약에서 어긋나네요.

2024-07-06 07:39 UTC, chadongmin commented on src/main/java/app/bottlenote/alcohols/service/domain/DefaultAlcoholDomainSupport.java
> +		return alcoholQueryRepository.findAlcoholInfoById(alcoholId, userId);
수정했습니다

2024-07-06 07:40 UTC, Whale0928 approved these changes
👀

2024-07-06 07:41 UTC, chadongmin commented on src/main/java/app/bottlenote/alcohols/service/domain/DefaultAlcoholDomainSupport.java
> +	public Optional<Alcohol> findById(Long alcoholId) {
수정했습니다

2024-07-06 07:41 UTC, merged