docs : 유저 프로필 이미지 변경 tec spec
bottle-note/bottle-note-api-server pull request #152
Opened 2024-06-30 06:40 UTC by 200wonman

Resolves #148

# 해결하려는 문제가 무엇인가요?

- 유저 프로필 이미지 변경 기능을 구현합니다.

# 어떻게 해결했나요?

- s3를 이용해 이미지 url을 USER테이블에 저장합니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?

- 이미지를 저장하는 코드작성 방법이 올바른지 체크 부탁드립니다.

## 참고 자료

-

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-07-03 20:20 UTC, Whale0928 requested changes

2024-07-03 20:20 UTC, Whale0928 commented on docs/tech-spec/user/user_profileImage_change.md
> +- `로그인 유저`(user_id)가 존재하는지 확인합니다.
프로파일을 업로드하는거면 이미지 경로의 패턴이나 요청을 날려봐서 이미지를 확인할수도 있을것 같네요

2024-07-03 20:20 UTC, Whale0928 commented on src/docs/asciidoc/api/user/user-profile-images-change.adoc
> +
그냥 이걸로 날려하는 것보다
어떤식으로 업데이트해야하는지 설명은 해줘야겟죠?

여기서는 상단의 이미지 업로드 api 문서를 참조해서 view url을 전달해라 라는 말이 잇으면 적절하겟네요

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/controller/UserCommandController.java
> +
의미없는 공백이 자주 , 많이 보이네요 이런 부분은 ide의 설정을 통해서나 직접 처리해 좀더 정확하게 관리하죠.

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/dto/request/ProfileImageChangeRequest.java
> +	String viewUrl
값 하나만 받는데 굳이 dto까지 만드는건 아닌거 같네요. 관습적인 코딩을 하지마세요.

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/controller/UserCommandController.java
> +	public ResponseEntity<GlobalResponse> profileImageChange(@RequestBody ProfileImageChangeRequest request) {
확인할 필요가 잇는게.
1. 
2. 값이 하나인대 dto를 사용하는것
2. valid 어노테이션이 누락된것 ( 테스트를 했으면 인지했을겁니다. )

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/domain/User.java
> +	public void changeProfileImage(ProfileImageChangeVO profileImageChangeVO) {
위와 동일한데 일급 객체를 쓰고 싶은거면 정확하게 알아보고 사용하세요.
이건 영문을 모르겠어요 . 값이 하나인대 왜 vo가 갑자기 나오는지.

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/dto/response/ProfileImageChangeResponse.java
> +			this.callback = new URL("https://bottle-note.com/api/v1/users/" + userId);
두분 모두 이런식으로 작성하던데,

`https://bottle-note.com/api/v1/users/{userId}` 에서 

`https://bottle-note.com/api/v1` 는 바뀔수 있는 값입니다.

그렇다면 어떻게 해야할까 고민해보죠.

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/service/UserCommandService.java
> +import static app.bottlenote.user.exception.UserExceptionCode.USER_NOT_FOUND;
`static import`는 잘 활용하면 가독성이 올라갑니다 , 잘썻네요.

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/service/UserCommandService.java
> +		ProfileImageChangeVO profileImageChangeVO = new ProfileImageChangeVO(imageUrl);
만약 일급 객체가 목적이면 ProfileImage라는 임베드 객체가 만들어져야지 
VO가 왜 필요한지 이해가 안갑니다 Vo가 뭔지 제대로 확인하고 수정하죠

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/service/UserCommandService.java
> +			.callback("https://bottle-note.com/api/v1/users/info" + userId)// 내정보 조회 페이지
여기서는 url를 직접 넘기는데 dto에서는 또 안쓰네요 ? 확인이 필요해보이네요

2024-07-03 20:20 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/vo/ProfileImageChangeVO.java
> +	public ProfileImageChangeVO(String imageUrl) {
임베드 객체면 여기서 검증이라도 되야했겟죠?
위에서 말하긴 했는데 생각하지 않고 관습적으로 관성적인 코딩을 하지마세요.

2024-07-04 02:03 UTC, 200wonman commented on src/main/java/app/bottlenote/user/controller/UserCommandController.java
> +	public ResponseEntity<GlobalResponse> profileImageChange(@RequestBody ProfileImageChangeRequest request) {
2. url이 null로 들어오면프로필이미지 삭제로 구현했기때문에 null체크를 하지않았습니다.
그럼 좀 더 로직을 개선하기위해서 아래 두가지 코드 수정사항을 생각해봤는데 어떠세요?

1. req DTO에 STATUS : delete, update 를 추가한다.
2. front에서 이미지 url이 null일때 STATUS가 delete면 삭제기때문에 예외발생 X
3. front에서 이미지url이 null일때 STATUS가 update면 이미지 업데이트 불가

2024-07-04 02:39 UTC, 200wonman commented on src/main/java/app/bottlenote/user/dto/response/ProfileImageChangeResponse.java
> +			this.callback = new URL("https://bottle-note.com/api/v1/users/" + userId);
어딘가 전역에서 https://bottle-note.com/api/v1 를 관리하고 저희는 가져와서 쓴다면 변경되어도 문제가없을 것 같습니다. 
나중에 추가적인 이슈를 빼서 작업을 진행하는게 좋을까요?

2024-07-04 06:34 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/dto/response/ProfileImageChangeResponse.java
> +			this.callback = new URL("https://bottle-note.com/api/v1/users/" + userId);
지금도 밖에서 주입해주는데 그 주입받는 값이 yml같은 곳에서 환경값으로 받아와도 되겟죠?

나중에 버저닝 이슈가 생기면 그때 수정하죠.

2024-07-04 06:36 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/controller/UserCommandController.java
> +	public ResponseEntity<GlobalResponse> profileImageChange(@RequestBody ProfileImageChangeRequest request) {
dto 자체가 무의미해보여요 코드만 늘리는것 같아요.

dto에 @NotNull이 이있어서 달았던건데 사용안하는 어노테이션을 때면 해결되겟죠?

별개로 null문자열이 들어오면 그대로 업데이트하는건 적절해보여요

다만 그냥 지우는것 보다 보틀노트 기본 이미지로 치환한다든가 하는 처리가 들어가면 좀더 깔끔할것 같네요.

2024-07-06 08:49 UTC, Whale0928 commented on src/test/java/app/bottlenote/docs/user/RestDocsUserChangeContollerTest.java
> +import static org.springframework.restdocs.payload.PayloadDocumentation.*;
'*' import ❌

2024-07-06 08:49 UTC, Whale0928 commented on src/docs/asciidoc/api/user/user-profile-images-change.adoc
> +변경할 이미지 url과 Status(update, delete)가 필요합니다.
확인 필요

2024-07-06 08:49 UTC, Whale0928 commented on src/docs/asciidoc/api/user/user-profile-images-change.adoc
> +변경할 이미지 url과 Status(update, delete)가 필요합니다.
확인 필요

2024-07-06 08:49 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/service/UserCommandService.java
> +
IDE 옵션 수정 필요  (의미없는 공백 관련)

2024-07-06 08:49 UTC, Whale0928 commented on src/docs/asciidoc/api/user/user-profile-images-change.adoc
> +변경할 이미지 url과 Status(update, delete)가 필요합니다.
확인 필요

2024-07-06 09:26 UTC, Whale0928 approved these changes
👀

2024-07-06 09:27 UTC, merged