리뷰상세조회 response에 수정이 필요하다
bottle-note/bottle-note-api-server pull request #173
Opened 2024-07-09 12:50 UTC by chadongmin

Resolves #{이슈-번호}

#171 

# 해결하려는 문제가 무엇인가요?

- 리뷰 목록조회에 불필요한 필드가 있어서 삭제했습니다.
- 리뷰 상세조회에서 댓글목록을 삭제하고, 베스트 리뷰 여부를 판별하는 로직을 추가했습니다.
- 가독성 향상을 위해 ReviewDetailResponse DTO 안에 내부 클래스를 사용해서 ReviewDetailInfo를 작성했습니다.
    - record로 작성해야 하지만, List 타입의 dto 주입 문제를 해결하지 못해서 부득이하게 class로 선언했습니다 (추후 수정예정입니다)

# 어떻게 해결했나요?

-

# 어떤 부분에 집중하여 리뷰해야 할까요?

-

## 참고 자료

-

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-07-09 13:37 UTC, 200wonman reviewed
주소가 삭제가됐던데 왜인지 궁금합니다 👀

2024-07-09 13:37 UTC, 200wonman commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
>  		this.isMyReview = isMyReview;
삭제된 주소관련 애들은 어디서 조회하나요?👀

2024-07-09 13:53 UTC, chadongmin commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
>  		this.isMyReview = isMyReview;
리뷰 목록 조회 / 내가 작성한 리뷰 조회 API에는 주소가 필요없는데 추가되어 있어서 삭제했습니다.
주소관련 정보들은 리뷰 상세조회에서 조회합니다

2024-07-09 17:35 UTC, Whale0928 requested changes
:eyes

2024-07-09 17:35 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
> -	private final String address;
목록의 반환 정보인걸 좀더 명확하게 나타내고 , 레코드로 변환해보죠

2024-07-09 17:35 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
> -	private final String address;
이 객체는 리뮤 목록시에만 사용될거 같은데 

이름을 바꾼거나 ReviewListResponse의 내부 클래스로 바꾼다를 생각해봐도 좋겟네요. 

`ReviewListResponse.ReviewInfo` 이런식으로 선언되면 리뷰 목록에서 

사용되는 리뷰의 목록으로 보기 좋을것 같네요.

<br>

**이너 클래스를 활용해 명확하게 나타내는 예** 

- `ReviewListResponse.ReviewInfo` : 리뷰 목록의 리뷰 정보 값
- `ReviewDetailResponse.ReviewInfo` : 상세 조회의 리뷰 정보 값
- `AlcoholsResponse.ReviewInfo` : 위스키 목록의 리뷰 정보 값

2024-07-09 17:37 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
> -	private final String address;
추가적으로 브랜치 명 앞에

`pr/`이 누락되네요 수정이 필요하고.

pr 명칭도 다른 두개 확인해서 이름 수정하죠.

2024-07-10 01:29 UTC, chadongmin commented on src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
> -	private final String address;
ReviewListResponse.ReviewInfo : 리뷰 목록의 리뷰 정보 값
ReviewDetailResponse.ReviewInfo : 상세 조회의 리뷰 정보 값
AlcoholsResponse.ReviewInfo : 위스키 목록의 리뷰 정보 값

위 형태로 수정완료 했습니다! 훨씬 가독성이 좋아보이네요

2024-07-10 01:56 UTC, Whale0928 approved these changes
👀

2024-07-10 05:55 UTC, merged