feat : 회원 탈퇴 기능을 구현한다
bottle-note/bottle-note-api-server pull request #207
Opened 2024-07-28 13:50 UTC by chadongmin

Resolves #{이슈-번호}
#196 

# 해결하려는 문제가 무엇인가요?

- 회원 탈퇴 기능을 구현합니다.

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-07-28 13:52 UTC, chadongmin commented on src/main/java/app/bottlenote/user/domain/User.java
> +		this.nickName = "WITHDRAWAL USER";
닉네임을 외부 로직에서 강제로 바꾸는 상황은 회원탈퇴 밖에 없을것같아서
따로 Enum으로 안빼고, 문자열 하드코딩해서 닉네임 바꾸도록 했는데 적절한 방식인지 모르겠네요

2024-07-28 14:06 UTC, Whale0928 requested changes
몇몇 확인사항이 있습니다. 아직 모두 구현된게 아니니 일부분만 코멘드 해두었습니다.

2024-07-28 14:06 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/controller/UserCommandController.java
> +	public ResponseEntity<GlobalResponse> withdrawUser() {
이번 pr에서 GlobalResponse.success가 아닌 GlobalResponse.ok으로 변경해보죠

2024-07-28 14:06 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/domain/User.java
> +		this.nickName = "WITHDRAWAL USER";
음 삭제된다고 해도 닉네임을 굳이 변경할 필요가 있을까요?

그리고 닉네임의 선언부를 보면

`@Column(name = "nick_name", nullable = false, unique = true)`이니 

두번째 회원 탈퇴시 오류가 발생하겠죠?

2024-07-28 14:06 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/dto/response/constant/UserResultMessage.java
> +
탈퇴 실패에 대한 메시지도 있으면 좋겠네요.

그리고 클래스명이 `UserResultMessage` 이니 어떤 유저의 결과 메시지인지 모르겟네요

전역적으로 쓸거면 그렇다는 javadoc를 추가하거나 , 이름을 한정해서 짓는게 더 예쁠것 같네요

2024-07-28 14:06 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/service/UserCommandService.java
> +	private final UserDomainSupport userDomainSupport;
유저 서비스내에서 유저 도메인 서포터를 부른다?

이상하다는 느낌이 바로 오네요. 제외하고 구현하죠 

이 서비스는 `사용자의 서비스모듈`입니다.

만약 `사용자의 서비스모듈` 에서 `술` 에 대한 정보가 필요한 경우 알코올 도메인 서포터가 있으면 좋겠지만 지금은 아니죠?

2024-07-28 14:06 UTC, Whale0928 commented on src/main/java/app/bottlenote/user/service/domain/DefaultUserDomainSupport.java
> +			.orElseThrow(() -> new UserException(USER_NOT_FOUND));
위에서 말했지만 여기서 필요한 메소드는 아닙니다. 

그리고 유저 탈퇴 시 더 고려해야하는건 없을까? 라는건 생각해보죠. 없다면 뭐가 생길수 있을지 주석으로라도 고민해보죠.

2024-07-29 11:47 UTC, chadongmin commented on src/main/java/app/bottlenote/user/service/UserCommandService.java
> +	private final UserDomainSupport userDomainSupport;
도메인 서포트를 사용하는 기준은 다른 모듈의 정보가 필요할때만 사용하는거군요
그러면 바로 User엔티티에 접근하는게 맞겠네요

2024-07-29 12:07 UTC, chadongmin commented on src/main/java/app/bottlenote/user/domain/User.java
> +		this.nickName = "WITHDRAWAL USER";
유니크 제약조건이 있어서 하드코딩해서 바꾸는건 잘못된 방식이네요
근데 탈퇴한 회원의 닉네임을 어떤 방식이든 바꿔주지 않으면, 새로 가입할 유저가 탈퇴한 회원이 사용한 닉네임을 사용못하는 문제가 발생할 것 같아요
그래서 탈퇴한 회원의 아이디를 "WITHDRAW"+{userId} 와 같은 식으로 유니크하도록 만들어주면 되지 않을까요?
어떻게 생각하시는지 궁금합니다.

2024-07-29 14:06 UTC, chadongmin commented on src/main/java/app/bottlenote/user/dto/response/constant/UserResultMessage.java
> +
수정했습니다.

2024-07-29 14:06 UTC, chadongmin commented on src/main/java/app/bottlenote/user/controller/UserCommandController.java
> +	public ResponseEntity<GlobalResponse> withdrawUser() {
수정했습니다.

2024-07-29 14:33 UTC, Whale0928 requested changes
몇몇 수정사항만 적용하고 내일 미팅 후 병합하도록 하죠.

2024-07-29 14:33 UTC, Whale0928 commented on src/test/java/app/bottlenote/user/controller/UserCommandControllerTest.java
> +@DisplayName("[unit] [controller] UserCommandChangeController")
`UserCommandChangeController` -> `UserCommand`

2024-07-29 14:33 UTC, Whale0928 commented on src/test/java/app/bottlenote/user/controller/UserCommandControllerTest.java
> +	@DisplayName("회원탈퇴에 실패한다.")
어떤 경우 `회원탈퇴에 실패한다` 일까요?

2024-07-29 14:33 UTC, Whale0928 commented on src/test/java/app/bottlenote/user/integration/UserCommandIntegrationTest.java
> +@DisplayName("[integration] [controller] UserCommandController")
위와 동일하게 이름 변경하기.

2024-07-29 14:33 UTC, Whale0928 commented on src/test/java/app/bottlenote/user/integration/UserCommandIntegrationTest.java
> +	private MockedStatic<SecurityContextUtil> mockedSecurityUtil;
통합 테스트에서는 모킹을 하지 않습니다. 화요일 미팅에서 한번 더 이야기하죠.

2024-07-29 14:33 UTC, Whale0928 commented on src/test/java/app/bottlenote/user/integration/UserCommandIntegrationTest.java
> +
화이트 스페이스 제거하기

2024-07-29 14:33 UTC, Whale0928 commented on src/test/java/app/bottlenote/user/integration/UserCommandIntegrationTest.java
> +		User withdrawUser = userCommandRepository.findById(user.getId())
.isPresent로 바꾸면 더욱 가독성 있겟네요. 👀

레포지토리를 가져오는건 좋은 생각. 👍

2024-07-29 14:33 UTC, Whale0928 commented on src/test/java/app/bottlenote/user/service/UserCommandServiceTest.java
> +		User user = UserObjectFixture.getUserObject();
이 시점에 이전 닉네임을 전달하면 검증할때 더욱 확실하겟죠?

지금은 유저에 어떤 값이 있는지 하나도 모르지만 픽스터를 

조금 수정해 이름,나이등 우리가 테스트 하고 싶은 값을 인자로 넘기는것이 좋겟네요.

그리고 유저 오브젝트가 아닌 유저 픽스터 오브젝트 같이 픽스쳐 오브젝트를 모두 명시하도록 하죠

2024-07-29 14:33 UTC, Whale0928 commented on src/test/resources/init-script/schema.sql
> +    `status`      varchar(255) NOT NULL COMMENT '사용자 상태',
아직 우리 디비에는 상태값 필드가 없으니깐 메인으로 병합 전 매우 주의해야겟네요?

2024-07-29 14:33 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/security/jwt/JwtTokenProvider.java
> +	public static final int ACCESS_TOKEN_EXPIRE_TIME = 3 * 60 * 60 * 1000; // 3hours
계속해서 변경이 일어나는데 변경이 유연하게 프로파일을 활용하도 좋겟네요.

2024-07-30 14:04 UTC, chadongmin commented on src/test/java/app/bottlenote/user/integration/UserCommandIntegrationTest.java
> +		User withdrawUser = userCommandRepository.findById(user.getId())
수정했습니다!

2024-07-30 14:16 UTC, Whale0928 approved these changes

2024-07-30 14:16 UTC, chadongmin commented on src/test/resources/init-script/schema.sql
> +    `status`      varchar(255) NOT NULL COMMENT '사용자 상태',
개발 디비에 컬럼 추가했습니다!

2024-07-30 14:17 UTC, merged