feat : 문의글 작성 기능을 구현한다.
bottle-note/bottle-note-api-server pull request #212
Opened 2024-08-01 12:47 UTC by chadongmin

Resolves #{이슈-번호}
#210 

# 해결하려는 문제가 무엇인가요?

- 문의글 작성 기능을 구현합니다.

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-08-08 10:25 UTC, Whale0928 requested changes
:eyes

2024-08-08 10:25 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/controller/HelpCommandController.java
> +			orElseThrow(() -> new UserException(USER_NOT_FOUND));
User Not Found -> Required User 로 변경이 필요해보이네요.

2024-08-08 10:25 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/domain/constant/HelpType.java
> +	WHISKEY,
1. convert가 필요합니다 ( Request 로 바로 받을 떄 사용)
2. 필드를 하나 추가해 각 범위에 어떤 종유의 예외인지 한글,영어로 알려주는 값을 추가 `String korDescription`

2024-08-08 10:25 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/repository/HelpRepository.java
> +
시나리오를 고려하면 특정 사용자 식별자를 가지고 조회하는것 + 특정 사용자의 미해결된걸 , 미해결된것등을 준비해놔도 좋겟네요

2024-08-10 08:07 UTC, chadongmin commented on src/main/java/app/bottlenote/support/help/controller/HelpCommandController.java
> +			orElseThrow(() -> new UserException(USER_NOT_FOUND));
수정했습니다!

2024-08-10 08:07 UTC, chadongmin commented on src/main/java/app/bottlenote/support/help/domain/constant/HelpType.java
> +	WHISKEY,
수정했습니다!

2024-08-10 08:08 UTC, chadongmin commented on src/main/java/app/bottlenote/support/help/repository/HelpRepository.java
> +
이 부분도 추가했습니다.

2024-08-10 08:15 UTC, Whale0928 approved these changes

2024-08-10 08:15 UTC, Whale0928 commented on src/test/java/app/bottlenote/support/help/fixture/HelpObjectFixture.java
> +			"로그인이 안돼요",
픽스처를 준비할때 이런 `내용`과 관련된 부분은 인자로 넘겨서 그걸 검증하는것도 좋습니다.
테스트 시에 검증하게 될때 왜 이런 문구가 등록되었지 라는 생각이 드는 부분은 아쉬운 여지가 있죠. 
나중에 다른 테스트 시에는 이걸 고려해서 개선해보죠

ex) 테스트에서 등록한 게시글의 내용이나 제목을 픽스처로 생성 -> 테스트에서는 제대로 등록됬는지 검증

2024-08-10 08:16 UTC, chadongmin commented on src/test/java/app/bottlenote/support/help/fixture/HelpObjectFixture.java
> +			"로그인이 안돼요",
넵 이 부분은 다음 PR에서 적용해볼게요!

2024-08-10 08:16 UTC, merged