feat : 리뷰 상태 변경 API를 개발한다.
bottle-note/bottle-note-api-server pull request #233
Opened 2024-08-27 15:25 UTC by chadongmin

Resolves #{이슈-번호}
#232 

# 해결하려는 문제가 무엇인가요?

- 리뷰 상태를 변경하는 API를 개발합니다.

---
# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-08-28 10:42 UTC, Whale0928 requested changes
통합테스트가 누락되었는데 추가하고 수정사항 코멘트 몇가지만 확인하죠

2024-08-28 10:42 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/exception/custom/code/ValidExceptionCode.java
> -	REQUIRED_REVIEW_ID(HttpStatus.BAD_REQUEST, "리뷰 아이디는 필수입니다."),
바로 아래랑 다른 목적이 있나요? `REVIEW_ID_REQUIRED`

2024-08-28 10:42 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/constant/ReviewResultMessage.java
> +	ACTIVE_SUCCESS("해당 리뷰가 활성화 되었습니다."),
활성화라는 개념이 공개 비공개로 판단해도 될것같네요

2024-08-28 11:35 UTC, chadongmin commented on src/main/java/app/bottlenote/global/exception/custom/code/ValidExceptionCode.java
> -	REQUIRED_REVIEW_ID(HttpStatus.BAD_REQUEST, "리뷰 아이디는 필수입니다."),
주예님이 수정한 부분이랑 합치면서 중복된 ExceptionCode가 포함되서 삭제했습니다

2024-08-28 11:35 UTC, chadongmin commented on src/main/java/app/bottlenote/review/dto/response/constant/ReviewResultMessage.java
> +	ACTIVE_SUCCESS("해당 리뷰가 활성화 되었습니다."),
공개/비공개로 수정하겠습니다. 그게 더 적절해보이네요

2024-08-28 11:40 UTC, chadongmin commented on src/main/java/app/bottlenote/review/dto/response/constant/ReviewResultMessage.java
> +	ACTIVE_SUCCESS("해당 리뷰가 활성화 되었습니다."),
ReviewActiveStatus(리뷰 활성상태)는 `활성`, `삭제`, `비활성`로 나뉩니다.
사용자 신고나, 스팸성 리뷰 등 시스템에 의해 제어되는 개념이고

ReviewDisplayStatus(리뷰 상태)는 `공개`, `비공개`로 나뉩니다.
사용자에 의해 공개상태, 비공개상태로 제어되는 개념이라

리뷰활성상태, 리뷰상태를 공개/비공개로 통일하기에는 논의가 필요해보입니다. 일단은 그냥 두고 스크럼때 논의해봐도 좋겠네요

2024-08-29 00:38 UTC, 200wonman commented on src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
> +				.andExpect(status().isBadRequest());
ratingControllerTest.java 파일 보시면 
isBadRequest() 시 에러메세지를 어떻게 만들었는지 보이실 거에요!
참고 부탁드립니다 ~

2024-08-29 10:58 UTC, chadongmin commented on src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
> +				.andExpect(status().isBadRequest());
참고해서 수정했습니다 !!

2024-08-29 11:58 UTC, merged