refactor : 리뷰 등록시 프론트에서 전달하는 주소 정보를 수정한다
bottle-note/bottle-note-api-server pull request #241
Opened 2024-09-09 11:56 UTC by chadongmin

Resolves #{이슈-번호}
#240 

# 해결하려는 문제가 무엇인가요?

- 기존 `우편번호` / `주소` / `상세주소` 에서
- `상호명` / `도로명 주소` / `카테고리` / `지도 URL` / `위도` / `경도` 컬럼으로 수정합니다.
- 영향을 받는 API와 테스트코드를 수정했습니다

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-09-09 12:02 UTC, Whale0928 requested changes

2024-09-09 12:02 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/domain/ReviewLocation.java
> +	private String barName;
그냥 name으로 하는게 좀더 정확하겟네요 조회값이 항상 bar라는 걔념을 나오진 않으니깐

ex.) 고기집에서 위스키를 먹고 리뷰할수 있음. 편의점에서 위스키를 구매할 수 있음

2024-09-09 12:06 UTC, chadongmin commented on src/main/java/app/bottlenote/review/domain/ReviewLocation.java
> +	private String barName;
그냥 name으로 하기엔 `상호명` 이랑 너무 매치가 안되는것 같아요. store_name은 어떠신가요?

2024-09-10 00:50 UTC, chadongmin commented on src/main/java/app/bottlenote/review/domain/ReviewLocation.java
> +	private String barName;
컬럼명 `location_name` , Java 필드 명 `name`으로 결정

2024-09-10 11:24 UTC, merged