feat : 문의글 수정 기능을 구현한다
bottle-note/bottle-note-api-server pull request #244
Opened 2024-09-11 11:09 UTC by chadongmin

Resolves #{이슈-번호}

#243 

# 해결하려는 문제가 무엇인가요?

- 문의글 수정 기능을 구현했습니다.
- 문의글 등록 RequestDto를 UpsertDto로 수정하여 재사용하도록 구현했습니다.
- 테스트코드 작성 예정

## 참고 자료

-

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-09-11 13:15 UTC, Whale0928 requested changes
전체적으로 잘 작성되었는데 IDE 임포트 설정 수정이 필요해보이네요

2024-09-11 13:15 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/domain/Help.java
> +import jakarta.persistence.*;
자동 임포트 설정 수정 필요

2024-09-11 13:15 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/domain/Help.java
> +	public void updateHelp(String title, String content, HelpType helpType){
Null 체크를 하는게 좋겟네요.

2024-09-11 13:59 UTC, chadongmin commented on src/main/java/app/bottlenote/support/help/domain/Help.java
> +	public void updateHelp(String title, String content, HelpType helpType){
넵!

2024-09-11 13:59 UTC, chadongmin commented on src/main/java/app/bottlenote/support/help/domain/Help.java
> +import jakarta.persistence.*;
앗... 바로 설정하겠슴다 👀

2024-09-12 08:07 UTC, dongmin-gn commented on src/main/java/app/bottlenote/support/help/domain/Help.java
> +import jakarta.persistence.*;
수정했어요

2024-09-12 08:08 UTC, chadongmin commented on src/main/java/app/bottlenote/support/help/domain/Help.java
> +import jakarta.persistence.*;
수정했어요

2024-09-12 08:11 UTC, Whale0928 approved these changes

2024-09-12 08:29 UTC, merged