feat :  문의글 조회 기능을 구현한다
bottle-note/bottle-note-api-server pull request #248
Opened 2024-09-19 12:36 UTC by chadongmin

Resolves #{이슈-번호}
#243 

# 해결하려는 문제가 무엇인가요?

- `문의글 목록 조회 API`  `문의글 상세 조회 API` 를 구현했습니다.

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-09-20 12:26 UTC, Whale0928 requested changes
전반적인 로직은 괜찮지만 몇가지 개선점이 보이네요

2024-09-20 12:26 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/security/SecurityConfig.java
> +				.requestMatchers("/api/v1/help/**").authenticated()
api 시트 정리하면서 인증 인가 필요한것도 확인 한번씩 더 하죠 시트에 필드도 추가하고
몇개 누락된게 좀 있을거같아요 . 검증이 필요한 엔드포인트들

2024-09-20 12:26 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/controller/HelpCommandController.java
> +		Long currentUserId = SecurityContextUtil.getUserIdByContext().orElse(-1L);
여기는 -1이 아닌 예외를 던져야하지 않을까요 ? 왜 -1을 했을까요 ? 

help 목록을 타인이 볼수 있는건가요?

본인의 목록만 확인해야하지 않을까요

2024-09-20 12:26 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/dto/request/HelpPageableRequest.java
> +public record HelpPageableRequest(
공통 페이지블 객체를 만들 필요성이 보이네요

2024-09-20 12:26 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/dto/response/HelpDetailInfo.java
> +	public static HelpDetailInfo of (Help help) {
엔티티 전체를 보내는건  부적절한 경계 침범이네요 빌더로 개선하죠.

2024-09-20 12:26 UTC, Whale0928 commented on src/main/java/app/bottlenote/support/help/repository/custom/CustomHelpQueryRepositoryImpl.java
> +	private CursorPageable getCursorPageable(
이거랑 아래 두개는 `HelpQuerySupporter` 으로 보내도 되겟네요

2024-09-30 13:32 UTC, Whale0928 reviewed
문서쪽 [discrete]만 추가후 병합하도록 하죠

2024-09-30 13:32 UTC, Whale0928 commented on src/docs/asciidoc/api/support/help/help-delete.adoc
> -==== Error code ====
삭제 하는게 아닌  [discrete] 만 붙히면 됩니다.
```
[discrete]
==== Error code ====
```

사이드바 확인 후 에러코드가 뜨는 것들도 [discrete]만 추가해두세요.

2024-09-30 14:35 UTC, chadongmin commented on src/docs/asciidoc/api/support/help/help-delete.adoc
> -==== Error code ====
반영했습니다. !

2024-09-30 14:36 UTC, merged