feat: The concept related to popularity was modified and applied.
bottle-note/bottle-note-api-server pull request #256
Opened 2024-10-14 00:40 UTC by Whale0928

Resolves #255 

# 해결하려는 문제가 무엇인가요?

- 인기도 관련 테이블을 적요했습니다.

# 어떻게 해결했나요?

- 인기도 관련 테이블을 적요했습니다.

# 어떤 부분에 집중하여 리뷰해야 할까요?

- 수정된 api spec 

---

# RCA 룰

r: 꼭 반영해 주세요. 적극적으로 고려해 주세요. (Request changes)  
c: 웬만하면 반영해 주세요. (Comment)  
a: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다. (Approve)

2024-10-16 14:29 UTC, chadongmin requested changes
코멘트 남겼습니다. !

2024-10-16 14:29 UTC, chadongmin commented on src/main/java/app/bottlenote/alcohols/controller/PopularQueryController.java
>  	public ResponseEntity<?> getPopularOfWeek(@RequestParam(defaultValue = "5") Integer top) {
top 이 변수가 top5에서 5와 같은 몇개까지 뽑을지를 나타내는 변수 같은데 변수명이 top이라서 좀 헷갈렸습니다. 굳이 안바꿔도 될 것 같지만 topCount나 topN 처럼 바꾸면 더 직관적으로 top 몇까지 뽑을지 정하는 변수라는 뜻을 나타낼 수 있을 것 같네요

2024-10-16 14:29 UTC, chadongmin commented on src/main/java/app/bottlenote/alcohols/repository/PopularQueryRepository.java
> +	List<Populars> getPopularOfWeeks(@Param("userId") Long userId, Pageable size);
여기서 Pageale 타입의 파라미터가 사용이 안되는 것 같습니다. 서비스코드에서 PagebleRequest을 만들어서 넘기던데 이유가 있나요?

2024-10-16 14:29 UTC, chadongmin reviewed
코멘트 남겼습니다.!

2024-10-16 14:54 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/controller/PopularQueryController.java
>  	public ResponseEntity<?> getPopularOfWeek(@RequestParam(defaultValue = "5") Integer top) {
이런 건 팀의 컨벤션을 기준으로 삼는게 좋습니다.
만약 소액정산 기준 , 비용 특수 등 걔념적으로 어려운 변수명이라면 미사여구를 붙여 정확하게 하는게 좋지만
이런 가벼운 함수 + 직관적인 목표가 있는 메소드의 경우는 미사여구가 오히려 가독성을 해칠거같네요.
오히려 제 입장에서는 topCount는 의미없이 길어보이고 topN의 N은 뭘 의미하는 거지? 라고 생각이 드니깐요

2024-10-16 14:55 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/repository/PopularQueryRepository.java
> +	List<Populars> getPopularOfWeeks(@Param("userId") Long userId, Pageable size);
찍어보면 확인할수 있지만 JPQL로 limit가 적용되지 않습니다.
이때 pageable 객체를 전달하면 자동으로 적용해주고 한번 확인해보죠. 우리가 넘기는 파라미터 만큼 사이즈가 조절되나.

2024-10-16 15:36 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/repository/PopularQueryRepository.java
> +	List<Populars> getPopularOfWeeks(@Param("userId") Long userId, Pageable size);
추가로 이 코멘트 확인후 동민님이 데브브랜치 병합후 pr 머지 좀 해주세요.

2024-10-17 00:26 UTC, chadongmin commented on src/main/java/app/bottlenote/alcohols/repository/PopularQueryRepository.java
> +	List<Populars> getPopularOfWeeks(@Param("userId") Long userId, Pageable size);
JPQL로 limit 적용 안되는건 처음 알았네요. 👍

2024-10-17 03:08 UTC, merged