리뷰 등록기능
bottle-note/bottle-note-api-server pull request #98
Opened 2024-05-23 13:22 UTC by chadongmin

2024-05-23 13:44 UTC, 200wonman commented on docs/tech-spec/review/review-create-techspec.md
> +### **Request**
계획에 리뷰등록에 필요한 요구사항들도 추가하는건 어떨까요?
개발할때, 방향을 잃으면 작성된 요구사항이 하나의 지도로써 길을 잃지않도록 할 수 있을것 같아요! 🍸

2024-05-23 13:44 UTC, 200wonman commented on docs/tech-spec/review/review-create-techspec.md
> +  - [ ] 파라미터로 전달받은 alcoholId로 위스키 조회(존재하지 않는다면 Exception)
비즈니스 로직에서 발생할 수 있는 상황들을 좀 더 구체적으로 적되
백엔드 개발자뿐만 아니라 프론트엔드, 기획자도 알 수 있는 용어로 희석해보면
다른 팀원들과의 의사소통과 기록에도 좀 더 좋은 문서로 남을 수 도 있을거같습니다! 🥃

2024-05-23 13:44 UTC, 200wonman commented on docs/tech-spec/review/review-create-techspec.md
> +  - [ ] currentUserId로 유저 조회(존재하지 않는다면 Exception)
예외만 따로 쭉 모으면 한눈에 보기도 편할거 같아요! 🍷

2024-05-29 13:14 UTC, Whale0928 requested changes
몇몇 개선사항이 있습니다 확인 후 다시 요청해주세요.

2024-05-29 13:14 UTC, Whale0928 commented on docs/tech-spec/review/review-create-techspec.md
> +## 요약(Summary)
미팅을 통해 이야기한 방식으로 개선해주세요 👍

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/exception/AlcoholException.java
> +public class AlcoholException extends AbstractCustomException {
👍

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/exception/AlcoholExceptionCode.java
> +	public String getMessage() {
null 말고 제대로된걸로 던지게 수정해야할거 같네요.

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/alcohols/repository/AlcoholQueryRepository.java
> +	Optional<Alcohol> findAlcoholById(Long id);
`findById` 로 사용해도 될거같아요.

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +	public ResponseEntity<GlobalResponse> createReviews(
메소드의 순서는 가급적 지키는게 꺠끗한 코드에 도움이 될것같아요
서비스/ 인터페이스에서와의 순서

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +		Long currentUserId = SecurityContextUtil.getUserIdByContext().orElse(null);
이 메소드는 무조건 유저가 있어야 하니 null이 아닌 예외를 던지죠

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/controller/ReviewController.java
> +		ReviewCreateResponse createdReview = reviewService.createReviews(reviewCreateRequest,
파라미터를 줄넘김으로 표현할거면 모두 다 줄넘김을 사용하거나 아니면 한줄에 모두 적거나 둘중 하나만 하죠

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
> +public record ReviewCreateRequest(
아직 없는거겟지만 valid 추가 필요해 보여요

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
> +	String content,
내용에 대한 검증이 필요해보여요 
- 사이즈

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
> +	LocationInfo locationInfo,
👍

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
> +	String imageUrl,
order ,view url (이름은 바껴도 됨) 값을 같는 객체가 필요해보이네요.
썸네일은 이 목록 첫번째 요소가 썸네일 되도 될것같네요

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/response/ReviewCreateResponse.java
> +public class ReviewCreateResponse {
메시지 객체가 추가되면 좋을것 같네요.
Lond id만 전달하기 위해 dto 생성하는건 안티패턴

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +	public ReviewCreateResponse createReviews(ReviewCreateRequest reviewCreateRequest,
트랜잭션 어노테이션을 메소드 레벨에서 관리하죠

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		Long currentUserid) {
동일한 서비스 내에서는 동일한 걔념으로 관리하죠
userid or currentUserid (카멜케이스 지키고)

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		User user = userCommandRepository.findById(currentUserid).orElseThrow(
메소드 ' . ' 포인트당 줄넘김 하면 가독성이 높아집니다.

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +			.imageUrl(reviewCreateRequest.imageUrl())
썸네일 이미지를 추출하는 과정이 필요하겟죠 ?

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +			.content(reviewCreateRequest.content())
내용에 대한 검증도 들어가면 좋을것가네요.

2024-05-29 13:14 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		return new ReviewCreateResponse(saveReview.getId());
new 생성자 보다 , 정적팩토리 메소드나 빌더 패턴을 한번 고려해보죠

2024-05-30 02:35 UTC, 200wonman commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +			.imageUrl(reviewCreateRequest.imageUrl())
reviewCreateRequest에서 꺼내는 값들을 필드 초기화 하고 코드를 수정하는건 어떨까요?🍹

2024-05-30 02:35 UTC, 200wonman commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		Alcohol alcohol = alcoholQueryRepository.findAlcoholById(reviewCreateRequest.alcoholId())
review에서 발생할만한exception 들이있으면 좋을거같아요🍺

2024-06-02 06:08 UTC, Whale0928 requested changes
확인 후 다시 pr 올려주세요.

2024-06-02 06:08 UTC, Whale0928 commented on docs/tech-spec/review/review-create-techspec.md
> +- 리뷰를 등록할때 이미지를 첨부할 수 있다. (작성하지 않아도 무방함)
괄호보다는 `선택적` 이라는 명식적인 표현이 들어가도 괜찮을듯 하네요

2024-06-02 06:08 UTC, Whale0928 commented on docs/tech-spec/review/review-create-techspec.md
> +- price값이 정상적인 값인지? (음수의 값이 들어올 수 없음 or 비상식적으로 높은 값
비상식적으로 높은값 X ,   100억 미만 등 명확한 요구사항이 필요

2024-06-02 06:08 UTC, Whale0928 commented on src/docs/asciidoc/api/review/review-create.adoc
> +=== 리뷰 조회 ===
리뷰등록

2024-06-02 06:08 UTC, Whale0928 commented on src/main/java/app/bottlenote/global/security/SecurityConfig.java
> +				.requestMatchers("/api/v1/reviews").authenticated()
Get 과 Post를 분리해서 처리해야합니다.

2024-06-02 06:08 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
> +		if (tastingTagList.isEmpty()) {
dto에서 처리할만한 로직은 아닌것 같아요 비지니스레이어에서 처리하죠

2024-06-02 06:08 UTC, Whale0928 commented on src/main/java/app/bottlenote/review/service/ReviewService.java
> +		reviewImageRepository.saveAll(reviewImageList);
https://velog.io/@wisepine/JPA-%EC%82%AC%EC%9A%A9-%EC%8B%9C-19%EA%B0%80%EC%A7%80-Tip#9-auto-increment-pk--bulk-insert%EB%8A%94-jpa%EA%B0%80-%EC%95%84%EB%8B%8C-jdbc%EB%A1%9C

벌크 insert가 좀더 적절해 보이네요

2024-06-02 06:08 UTC, Whale0928 commented on src/test/java/app/bottlenote/review/controller/ReviewCreateControllerTest.java
> +class ReviewCreateControllerTest {
등록 실패에 대한 테스트도 있으면 좋을것 같네요.

2024-06-02 06:08 UTC, Whale0928 commented on src/test/java/app/bottlenote/review/controller/ReviewCreateRequestTest.java
> +class ReviewCreateRequestTest {
dto를 테스트할 필요가 있을까요 ?

2024-06-03 15:36 UTC, closed without merging